export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_CREATE_REQUEST = "BRAND_CREATE_REQUEST";
export const BRAND_UPDATE_REQUEST = "BRAND_UPDATE_REQUEST";
export const BRAND_DELETE_REQUEST = "BRAND_DELETE_REQUEST";
